language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
before_install:
  - gem update --system
  - gem install bundler -v 1.17.3
gemfile:
  - gemfiles/middleman_3.3.gemfile
  - gemfiles/middleman_3.4.gemfile
  - gemfiles/middleman_3_stable.gemfile
  - gemfiles/middleman_4.0.gemfile
  - gemfiles/middleman_4.1.gemfile
  - gemfiles/middleman_4.2.gemfile
  - gemfiles/middleman_master.gemfile
